[2023-01-27 15:50:19 +1300] [11394] [INFO] Starting gunicorn 20.1.0
[2023-01-27 15:50:19 +1300] [11394] [INFO] Listening at: unix:flaskrest.sock (11394)
[2023-01-27 15:50:19 +1300] [11394] [INFO] Using worker: sync
[2023-01-27 15:50:19 +1300] [11397] [INFO] Booting worker with pid: 11397
[2023-01-27 15:50:19 +1300] [11398] [INFO] Booting worker with pid: 11398
[2023-01-27 15:50:19 +1300] [11399] [INFO] Booting worker with pid: 11399
[2023-01-27 15:50:19 +1300] [11400] [INFO] Booting worker with pid: 11400
[2023-01-27 15:50:19 +1300] [11401] [INFO] Booting worker with pid: 11401
[2023-01-27 15:50:19 +1300] [11402] [INFO] Booting worker with pid: 11402
[2023-01-27 15:50:19 +1300] [11403] [INFO] Booting worker with pid: 11403
[2023-01-27 15:50:19 +1300] [11404] [INFO] Booting worker with pid: 11404
[2023-01-27 15:50:19 +1300] [11405] [INFO] Booting worker with pid: 11405
[2023-01-27 16:32:08 +1300] [11404] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11402] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11401] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11405] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11403] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11397] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11399] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11400] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11398] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:32:08 +1300] [11400] [INFO] Worker exiting (pid: 11400)
[2023-01-27 16:32:08 +1300] [11401] [INFO] Worker exiting (pid: 11401)
[2023-01-27 16:32:08 +1300] [11405] [INFO] Worker exiting (pid: 11405)
[2023-01-27 16:32:08 +1300] [11403] [INFO] Worker exiting (pid: 11403)
[2023-01-27 16:32:08 +1300] [11398] [INFO] Worker exiting (pid: 11398)
[2023-01-27 16:32:08 +1300] [11404] [INFO] Worker exiting (pid: 11404)
[2023-01-27 16:32:08 +1300] [11399] [INFO] Worker exiting (pid: 11399)
[2023-01-27 16:32:08 +1300] [11397] [INFO] Worker exiting (pid: 11397)
[2023-01-27 16:32:08 +1300] [11402] [INFO] Worker exiting (pid: 11402)
[2023-01-27 16:32:09 +1300] [12484] [INFO] Booting worker with pid: 12484
[2023-01-27 16:32:09 +1300] [12485] [INFO] Booting worker with pid: 12485
[2023-01-27 16:32:09 +1300] [12486] [INFO] Booting worker with pid: 12486
[2023-01-27 16:32:10 +1300] [12485] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:32:10 +1300] [12486] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:32:10 +1300] [12484] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:32:10 +1300] [12490] [INFO] Booting worker with pid: 12490
[2023-01-27 16:32:10 +1300] [12490] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:32:10 +1300] [12492] [INFO] Booting worker with pid: 12492
[2023-01-27 16:32:10 +1300] [12493] [INFO] Booting worker with pid: 12493
[2023-01-27 16:32:10 +1300] [12492] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:32:10 +1300] [12495] [INFO] Booting worker with pid: 12495
[2023-01-27 16:32:10 +1300] [12496] [INFO] Booting worker with pid: 12496
[2023-01-27 16:32:10 +1300] [12493] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:32:10 +1300] [12495] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:32:10 +1300] [12496] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:32:10 +1300] [12500] [INFO] Booting worker with pid: 12500
[2023-01-27 16:32:10 +1300] [12500] [ERROR] unexpected indent (index.py, line 34)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 34
    	def index():
    ^
IndentationError: unexpected indent
[2023-01-27 16:36:44 +1300] [12486] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12486] [INFO] Worker exiting (pid: 12486)
[2023-01-27 16:36:44 +1300] [12484] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12490] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12490] [INFO] Worker exiting (pid: 12490)
[2023-01-27 16:36:44 +1300] [12485] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12485] [INFO] Worker exiting (pid: 12485)
[2023-01-27 16:36:44 +1300] [12492] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12484] [INFO] Worker exiting (pid: 12484)
[2023-01-27 16:36:44 +1300] [12492] [INFO] Worker exiting (pid: 12492)
[2023-01-27 16:36:44 +1300] [12500] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12500] [INFO] Worker exiting (pid: 12500)
[2023-01-27 16:36:44 +1300] [12496] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12496] [INFO] Worker exiting (pid: 12496)
[2023-01-27 16:36:44 +1300] [12495] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12493] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:36:44 +1300] [12495] [INFO] Worker exiting (pid: 12495)
[2023-01-27 16:36:44 +1300] [12493] [INFO] Worker exiting (pid: 12493)
[2023-01-27 16:36:45 +1300] [12675] [INFO] Booting worker with pid: 12675
[2023-01-27 16:36:45 +1300] [12676] [INFO] Booting worker with pid: 12676
[2023-01-27 16:36:45 +1300] [12677] [INFO] Booting worker with pid: 12677
[2023-01-27 16:36:45 +1300] [12678] [INFO] Booting worker with pid: 12678
[2023-01-27 16:36:45 +1300] [12679] [INFO] Booting worker with pid: 12679
[2023-01-27 16:36:45 +1300] [12680] [INFO] Booting worker with pid: 12680
[2023-01-27 16:36:45 +1300] [12681] [INFO] Booting worker with pid: 12681
[2023-01-27 16:36:45 +1300] [12682] [INFO] Booting worker with pid: 12682
[2023-01-27 16:36:45 +1300] [12683] [INFO] Booting worker with pid: 12683
[2023-01-27 16:37:52 +1300] [12679] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:52 +1300] [12683] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:52 +1300] [12679] [INFO] Worker exiting (pid: 12679)
[2023-01-27 16:37:52 +1300] [12683] [INFO] Worker exiting (pid: 12683)
[2023-01-27 16:37:52 +1300] [12681] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:52 +1300] [12681] [INFO] Worker exiting (pid: 12681)
[2023-01-27 16:37:52 +1300] [12747] [INFO] Booting worker with pid: 12747
[2023-01-27 16:37:52 +1300] [12678] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:52 +1300] [12675] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:52 +1300] [12675] [INFO] Worker exiting (pid: 12675)
[2023-01-27 16:37:52 +1300] [12678] [INFO] Worker exiting (pid: 12678)
[2023-01-27 16:37:52 +1300] [12748] [INFO] Booting worker with pid: 12748
[2023-01-27 16:37:52 +1300] [12749] [INFO] Booting worker with pid: 12749
[2023-01-27 16:37:53 +1300] [12677] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:53 +1300] [12677] [INFO] Worker exiting (pid: 12677)
[2023-01-27 16:37:53 +1300] [12680] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:53 +1300] [12680] [INFO] Worker exiting (pid: 12680)
[2023-01-27 16:37:53 +1300] [12750] [INFO] Booting worker with pid: 12750
[2023-01-27 16:37:53 +1300] [12676] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:53 +1300] [12682] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:37:53 +1300] [12676] [INFO] Worker exiting (pid: 12676)
[2023-01-27 16:37:53 +1300] [12682] [INFO] Worker exiting (pid: 12682)
[2023-01-27 16:37:53 +1300] [12751] [INFO] Booting worker with pid: 12751
[2023-01-27 16:37:53 +1300] [12753] [INFO] Booting worker with pid: 12753
[2023-01-27 16:37:54 +1300] [12754] [INFO] Booting worker with pid: 12754
[2023-01-27 16:37:54 +1300] [12755] [INFO] Booting worker with pid: 12755
[2023-01-27 16:37:54 +1300] [12756] [INFO] Booting worker with pid: 12756
[2023-01-27 16:40:49 +1300] [12751] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12751] [INFO] Worker exiting (pid: 12751)
[2023-01-27 16:40:49 +1300] [12748] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12748] [INFO] Worker exiting (pid: 12748)
[2023-01-27 16:40:49 +1300] [12747] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12747] [INFO] Worker exiting (pid: 12747)
[2023-01-27 16:40:49 +1300] [12750] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12750] [INFO] Worker exiting (pid: 12750)
[2023-01-27 16:40:49 +1300] [12753] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12753] [INFO] Worker exiting (pid: 12753)
[2023-01-27 16:40:49 +1300] [12756] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12755] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12754] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12749] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:40:49 +1300] [12755] [INFO] Worker exiting (pid: 12755)
[2023-01-27 16:40:49 +1300] [12754] [INFO] Worker exiting (pid: 12754)
[2023-01-27 16:40:49 +1300] [12749] [INFO] Worker exiting (pid: 12749)
[2023-01-27 16:40:49 +1300] [12756] [INFO] Worker exiting (pid: 12756)
[2023-01-27 16:40:50 +1300] [12842] [INFO] Booting worker with pid: 12842
[2023-01-27 16:40:50 +1300] [12843] [INFO] Booting worker with pid: 12843
[2023-01-27 16:40:50 +1300] [12844] [INFO] Booting worker with pid: 12844
[2023-01-27 16:40:50 +1300] [12845] [INFO] Booting worker with pid: 12845
[2023-01-27 16:40:50 +1300] [12846] [INFO] Booting worker with pid: 12846
[2023-01-27 16:40:50 +1300] [12847] [INFO] Booting worker with pid: 12847
[2023-01-27 16:40:50 +1300] [12848] [INFO] Booting worker with pid: 12848
[2023-01-27 16:40:50 +1300] [12849] [INFO] Booting worker with pid: 12849
[2023-01-27 16:40:51 +1300] [12850] [INFO] Booting worker with pid: 12850
[2023-01-27 16:42:53 +1300] [12844] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12844] [INFO] Worker exiting (pid: 12844)
[2023-01-27 16:42:53 +1300] [12842] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12842] [INFO] Worker exiting (pid: 12842)
[2023-01-27 16:42:53 +1300] [12845] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12845] [INFO] Worker exiting (pid: 12845)
[2023-01-27 16:42:53 +1300] [12843] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12843] [INFO] Worker exiting (pid: 12843)
[2023-01-27 16:42:53 +1300] [12847] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12847] [INFO] Worker exiting (pid: 12847)
[2023-01-27 16:42:53 +1300] [12848] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12848] [INFO] Worker exiting (pid: 12848)
[2023-01-27 16:42:53 +1300] [12849] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12849] [INFO] Worker exiting (pid: 12849)
[2023-01-27 16:42:53 +1300] [12846] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12850] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:42:53 +1300] [12846] [INFO] Worker exiting (pid: 12846)
[2023-01-27 16:42:53 +1300] [12850] [INFO] Worker exiting (pid: 12850)
[2023-01-27 16:42:54 +1300] [12890] [INFO] Booting worker with pid: 12890
[2023-01-27 16:42:54 +1300] [12892] [INFO] Booting worker with pid: 12892
[2023-01-27 16:42:54 +1300] [12893] [INFO] Booting worker with pid: 12893
[2023-01-27 16:42:54 +1300] [12894] [INFO] Booting worker with pid: 12894
[2023-01-27 16:42:54 +1300] [12895] [INFO] Booting worker with pid: 12895
[2023-01-27 16:42:55 +1300] [12896] [INFO] Booting worker with pid: 12896
[2023-01-27 16:42:55 +1300] [12897] [INFO] Booting worker with pid: 12897
[2023-01-27 16:42:55 +1300] [12898] [INFO] Booting worker with pid: 12898
[2023-01-27 16:42:55 +1300] [12899] [INFO] Booting worker with pid: 12899
[2023-01-27 16:44:05 +1300] [12893] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:05 +1300] [12893] [INFO] Worker exiting (pid: 12893)
[2023-01-27 16:44:05 +1300] [12890] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:05 +1300] [12890] [INFO] Worker exiting (pid: 12890)
[2023-01-27 16:44:05 +1300] [12898] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:05 +1300] [12898] [INFO] Worker exiting (pid: 12898)
[2023-01-27 16:44:05 +1300] [12895] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:05 +1300] [12895] [INFO] Worker exiting (pid: 12895)
[2023-01-27 16:44:05 +1300] [12894] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:05 +1300] [12894] [INFO] Worker exiting (pid: 12894)
[2023-01-27 16:44:05 +1300] [12892] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:05 +1300] [12892] [INFO] Worker exiting (pid: 12892)
[2023-01-27 16:44:05 +1300] [12897] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:05 +1300] [12896] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:05 +1300] [12896] [INFO] Worker exiting (pid: 12896)
[2023-01-27 16:44:05 +1300] [12897] [INFO] Worker exiting (pid: 12897)
[2023-01-27 16:44:05 +1300] [12968] [INFO] Booting worker with pid: 12968
[2023-01-27 16:44:05 +1300] [12969] [INFO] Booting worker with pid: 12969
[2023-01-27 16:44:06 +1300] [12899] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:44:06 +1300] [12899] [INFO] Worker exiting (pid: 12899)
[2023-01-27 16:44:06 +1300] [12970] [INFO] Booting worker with pid: 12970
[2023-01-27 16:44:06 +1300] [12971] [INFO] Booting worker with pid: 12971
[2023-01-27 16:44:06 +1300] [12972] [INFO] Booting worker with pid: 12972
[2023-01-27 16:44:06 +1300] [12973] [INFO] Booting worker with pid: 12973
[2023-01-27 16:44:06 +1300] [12974] [INFO] Booting worker with pid: 12974
[2023-01-27 16:44:06 +1300] [12975] [INFO] Booting worker with pid: 12975
[2023-01-27 16:44:07 +1300] [12976] [INFO] Booting worker with pid: 12976
[2023-01-27 16:51:07 +1300] [12971] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12970] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12970] [INFO] Worker exiting (pid: 12970)
[2023-01-27 16:51:07 +1300] [12971] [INFO] Worker exiting (pid: 12971)
[2023-01-27 16:51:07 +1300] [12974] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12974] [INFO] Worker exiting (pid: 12974)
[2023-01-27 16:51:07 +1300] [12975] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12975] [INFO] Worker exiting (pid: 12975)
[2023-01-27 16:51:07 +1300] [12972] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12972] [INFO] Worker exiting (pid: 12972)
[2023-01-27 16:51:07 +1300] [12976] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12973] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12976] [INFO] Worker exiting (pid: 12976)
[2023-01-27 16:51:07 +1300] [12973] [INFO] Worker exiting (pid: 12973)
[2023-01-27 16:51:07 +1300] [12968] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12968] [INFO] Worker exiting (pid: 12968)
[2023-01-27 16:51:07 +1300] [12969] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:07 +1300] [12969] [INFO] Worker exiting (pid: 12969)
[2023-01-27 16:51:08 +1300] [13114] [INFO] Booting worker with pid: 13114
[2023-01-27 16:51:08 +1300] [13114] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:08 +1300] [13116] [INFO] Booting worker with pid: 13116
[2023-01-27 16:51:08 +1300] [13116] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:08 +1300] [13118] [INFO] Booting worker with pid: 13118
[2023-01-27 16:51:08 +1300] [13118] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:08 +1300] [13119] [INFO] Booting worker with pid: 13119
[2023-01-27 16:51:08 +1300] [13121] [INFO] Booting worker with pid: 13121
[2023-01-27 16:51:08 +1300] [13119] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:08 +1300] [13123] [INFO] Booting worker with pid: 13123
[2023-01-27 16:51:08 +1300] [13121] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:08 +1300] [13123] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:08 +1300] [13126] [INFO] Booting worker with pid: 13126
[2023-01-27 16:51:08 +1300] [13126] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:08 +1300] [13128] [INFO] Booting worker with pid: 13128
[2023-01-27 16:51:08 +1300] [13128] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:08 +1300] [13130] [INFO] Booting worker with pid: 13130
[2023-01-27 16:51:08 +1300] [13130] [ERROR] 'return' outside function (index.py, line 50)
Traceback (most recent call last):
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/var/www/piapp/api_app/index.py", line 50
    return render_template('create.html')
    ^
SyntaxError: 'return' outside function
[2023-01-27 16:51:17 +1300] [13114] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13114] [INFO] Worker exiting (pid: 13114)
[2023-01-27 16:51:17 +1300] [13116] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13116] [INFO] Worker exiting (pid: 13116)
[2023-01-27 16:51:17 +1300] [13146] [INFO] Booting worker with pid: 13146
[2023-01-27 16:51:17 +1300] [13118] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13118] [INFO] Worker exiting (pid: 13118)
[2023-01-27 16:51:17 +1300] [13147] [INFO] Booting worker with pid: 13147
[2023-01-27 16:51:17 +1300] [13119] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13119] [INFO] Worker exiting (pid: 13119)
[2023-01-27 16:51:17 +1300] [13121] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13121] [INFO] Worker exiting (pid: 13121)
[2023-01-27 16:51:17 +1300] [13123] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13123] [INFO] Worker exiting (pid: 13123)
[2023-01-27 16:51:17 +1300] [13126] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13126] [INFO] Worker exiting (pid: 13126)
[2023-01-27 16:51:17 +1300] [13128] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13128] [INFO] Worker exiting (pid: 13128)
[2023-01-27 16:51:17 +1300] [13148] [INFO] Booting worker with pid: 13148
[2023-01-27 16:51:17 +1300] [13130] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:17 +1300] [13130] [INFO] Worker exiting (pid: 13130)
[2023-01-27 16:51:18 +1300] [13149] [INFO] Booting worker with pid: 13149
[2023-01-27 16:51:18 +1300] [13150] [INFO] Booting worker with pid: 13150
[2023-01-27 16:51:18 +1300] [13151] [INFO] Booting worker with pid: 13151
[2023-01-27 16:51:18 +1300] [13152] [INFO] Booting worker with pid: 13152
[2023-01-27 16:51:18 +1300] [13153] [INFO] Booting worker with pid: 13153
[2023-01-27 16:51:18 +1300] [13154] [INFO] Booting worker with pid: 13154
[2023-01-27 16:51:20 +1300] [13147] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:20 +1300] [13147] [INFO] Worker exiting (pid: 13147)
[2023-01-27 16:51:21 +1300] [13166] [INFO] Booting worker with pid: 13166
[2023-01-27 16:51:21 +1300] [13151] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:21 +1300] [13151] [INFO] Worker exiting (pid: 13151)
[2023-01-27 16:51:21 +1300] [13150] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:21 +1300] [13150] [INFO] Worker exiting (pid: 13150)
[2023-01-27 16:51:21 +1300] [13149] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:21 +1300] [13149] [INFO] Worker exiting (pid: 13149)
[2023-01-27 16:51:21 +1300] [13153] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:21 +1300] [13153] [INFO] Worker exiting (pid: 13153)
[2023-01-27 16:51:21 +1300] [13154] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:21 +1300] [13154] [INFO] Worker exiting (pid: 13154)
[2023-01-27 16:51:21 +1300] [13167] [INFO] Booting worker with pid: 13167
[2023-01-27 16:51:21 +1300] [13148] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:21 +1300] [13148] [INFO] Worker exiting (pid: 13148)
[2023-01-27 16:51:21 +1300] [13152] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:21 +1300] [13152] [INFO] Worker exiting (pid: 13152)
[2023-01-27 16:51:21 +1300] [13146] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 16:51:21 +1300] [13146] [INFO] Worker exiting (pid: 13146)
[2023-01-27 16:51:22 +1300] [13168] [INFO] Booting worker with pid: 13168
[2023-01-27 16:51:22 +1300] [13170] [INFO] Booting worker with pid: 13170
[2023-01-27 16:51:22 +1300] [13171] [INFO] Booting worker with pid: 13171
[2023-01-27 16:51:22 +1300] [13172] [INFO] Booting worker with pid: 13172
[2023-01-27 16:51:22 +1300] [13173] [INFO] Booting worker with pid: 13173
[2023-01-27 16:51:22 +1300] [13175] [INFO] Booting worker with pid: 13175
[2023-01-27 16:51:22 +1300] [13174] [INFO] Booting worker with pid: 13174
[2023-01-27 17:03:00 +1300] [13173] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:00 +1300] [13173] [INFO] Worker exiting (pid: 13173)
[2023-01-27 17:03:01 +1300] [13166] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:01 +1300] [13168] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:01 +1300] [13166] [INFO] Worker exiting (pid: 13166)
[2023-01-27 17:03:01 +1300] [13168] [INFO] Worker exiting (pid: 13168)
[2023-01-27 17:03:01 +1300] [13175] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:01 +1300] [13175] [INFO] Worker exiting (pid: 13175)
[2023-01-27 17:03:01 +1300] [13170] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:01 +1300] [13172] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:01 +1300] [13171] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:01 +1300] [13172] [INFO] Worker exiting (pid: 13172)
[2023-01-27 17:03:01 +1300] [13170] [INFO] Worker exiting (pid: 13170)
[2023-01-27 17:03:01 +1300] [13174] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:01 +1300] [13167] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:03:01 +1300] [13171] [INFO] Worker exiting (pid: 13171)
[2023-01-27 17:03:01 +1300] [13174] [INFO] Worker exiting (pid: 13174)
[2023-01-27 17:03:01 +1300] [13167] [INFO] Worker exiting (pid: 13167)
[2023-01-27 17:03:01 +1300] [13613] [INFO] Booting worker with pid: 13613
[2023-01-27 17:03:01 +1300] [13614] [INFO] Booting worker with pid: 13614
[2023-01-27 17:03:02 +1300] [13616] [INFO] Booting worker with pid: 13616
[2023-01-27 17:03:02 +1300] [13617] [INFO] Booting worker with pid: 13617
[2023-01-27 17:03:02 +1300] [13618] [INFO] Booting worker with pid: 13618
[2023-01-27 17:03:02 +1300] [13619] [INFO] Booting worker with pid: 13619
[2023-01-27 17:03:02 +1300] [13620] [INFO] Booting worker with pid: 13620
[2023-01-27 17:03:02 +1300] [13621] [INFO] Booting worker with pid: 13621
[2023-01-27 17:03:02 +1300] [13622] [INFO] Booting worker with pid: 13622
[2023-01-27 17:06:50 +1300] [13617] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13617] [INFO] Worker exiting (pid: 13617)
[2023-01-27 17:06:50 +1300] [13620] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13620] [INFO] Worker exiting (pid: 13620)
[2023-01-27 17:06:50 +1300] [13816] [INFO] Booting worker with pid: 13816
[2023-01-27 17:06:50 +1300] [13622] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13622] [INFO] Worker exiting (pid: 13622)
[2023-01-27 17:06:50 +1300] [13619] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13621] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13616] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13618] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13618] [INFO] Worker exiting (pid: 13618)
[2023-01-27 17:06:50 +1300] [13619] [INFO] Worker exiting (pid: 13619)
[2023-01-27 17:06:50 +1300] [13616] [INFO] Worker exiting (pid: 13616)
[2023-01-27 17:06:50 +1300] [13614] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13614] [INFO] Worker exiting (pid: 13614)
[2023-01-27 17:06:50 +1300] [13621] [INFO] Worker exiting (pid: 13621)
[2023-01-27 17:06:50 +1300] [13817] [INFO] Booting worker with pid: 13817
[2023-01-27 17:06:50 +1300] [13613] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:06:50 +1300] [13613] [INFO] Worker exiting (pid: 13613)
[2023-01-27 17:06:51 +1300] [13818] [INFO] Booting worker with pid: 13818
[2023-01-27 17:06:51 +1300] [13819] [INFO] Booting worker with pid: 13819
[2023-01-27 17:06:51 +1300] [13820] [INFO] Booting worker with pid: 13820
[2023-01-27 17:06:51 +1300] [13822] [INFO] Booting worker with pid: 13822
[2023-01-27 17:06:51 +1300] [13823] [INFO] Booting worker with pid: 13823
[2023-01-27 17:06:51 +1300] [13824] [INFO] Booting worker with pid: 13824
[2023-01-27 17:06:52 +1300] [13825] [INFO] Booting worker with pid: 13825
[2023-01-27 17:08:06 +1300] [13818] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13818] [INFO] Worker exiting (pid: 13818)
[2023-01-27 17:08:06 +1300] [13819] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13824] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13819] [INFO] Worker exiting (pid: 13819)
[2023-01-27 17:08:06 +1300] [13824] [INFO] Worker exiting (pid: 13824)
[2023-01-27 17:08:06 +1300] [13822] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13822] [INFO] Worker exiting (pid: 13822)
[2023-01-27 17:08:06 +1300] [13823] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13823] [INFO] Worker exiting (pid: 13823)
[2023-01-27 17:08:06 +1300] [13825] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13825] [INFO] Worker exiting (pid: 13825)
[2023-01-27 17:08:06 +1300] [13816] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13816] [INFO] Worker exiting (pid: 13816)
[2023-01-27 17:08:06 +1300] [13817] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13817] [INFO] Worker exiting (pid: 13817)
[2023-01-27 17:08:06 +1300] [13820] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:06 +1300] [13820] [INFO] Worker exiting (pid: 13820)
[2023-01-27 17:08:06 +1300] [13947] [INFO] Booting worker with pid: 13947
[2023-01-27 17:08:06 +1300] [13948] [INFO] Booting worker with pid: 13948
[2023-01-27 17:08:07 +1300] [13949] [INFO] Booting worker with pid: 13949
[2023-01-27 17:08:07 +1300] [13950] [INFO] Booting worker with pid: 13950
[2023-01-27 17:08:07 +1300] [13951] [INFO] Booting worker with pid: 13951
[2023-01-27 17:08:07 +1300] [13952] [INFO] Booting worker with pid: 13952
[2023-01-27 17:08:07 +1300] [13953] [INFO] Booting worker with pid: 13953
[2023-01-27 17:08:07 +1300] [13954] [INFO] Booting worker with pid: 13954
[2023-01-27 17:08:07 +1300] [13955] [INFO] Booting worker with pid: 13955
[2023-01-27 17:08:10 +1300] [13947] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:10 +1300] [13947] [INFO] Worker exiting (pid: 13947)
[2023-01-27 17:08:10 +1300] [13950] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:10 +1300] [13950] [INFO] Worker exiting (pid: 13950)
[2023-01-27 17:08:10 +1300] [13953] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:10 +1300] [13953] [INFO] Worker exiting (pid: 13953)
[2023-01-27 17:08:10 +1300] [13949] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:10 +1300] [13949] [INFO] Worker exiting (pid: 13949)
[2023-01-27 17:08:10 +1300] [13948] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:10 +1300] [13948] [INFO] Worker exiting (pid: 13948)
[2023-01-27 17:08:10 +1300] [13952] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:10 +1300] [13952] [INFO] Worker exiting (pid: 13952)
[2023-01-27 17:08:10 +1300] [13966] [INFO] Booting worker with pid: 13966
[2023-01-27 17:08:10 +1300] [13951] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:10 +1300] [13951] [INFO] Worker exiting (pid: 13951)
[2023-01-27 17:08:11 +1300] [13954] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:11 +1300] [13954] [INFO] Worker exiting (pid: 13954)
[2023-01-27 17:08:11 +1300] [13955] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:08:11 +1300] [13955] [INFO] Worker exiting (pid: 13955)
[2023-01-27 17:08:11 +1300] [13968] [INFO] Booting worker with pid: 13968
[2023-01-27 17:08:11 +1300] [13969] [INFO] Booting worker with pid: 13969
[2023-01-27 17:08:11 +1300] [13970] [INFO] Booting worker with pid: 13970
[2023-01-27 17:08:11 +1300] [13971] [INFO] Booting worker with pid: 13971
[2023-01-27 17:08:11 +1300] [13972] [INFO] Booting worker with pid: 13972
[2023-01-27 17:08:12 +1300] [13973] [INFO] Booting worker with pid: 13973
[2023-01-27 17:08:12 +1300] [13975] [INFO] Booting worker with pid: 13975
[2023-01-27 17:08:12 +1300] [13976] [INFO] Booting worker with pid: 13976
[2023-01-27 17:10:01 +1300] [13968] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13968] [INFO] Worker exiting (pid: 13968)
[2023-01-27 17:10:01 +1300] [13969] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13969] [INFO] Worker exiting (pid: 13969)
[2023-01-27 17:10:01 +1300] [13970] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13970] [INFO] Worker exiting (pid: 13970)
[2023-01-27 17:10:01 +1300] [13971] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13973] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13971] [INFO] Worker exiting (pid: 13971)
[2023-01-27 17:10:01 +1300] [13973] [INFO] Worker exiting (pid: 13973)
[2023-01-27 17:10:01 +1300] [13972] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13972] [INFO] Worker exiting (pid: 13972)
[2023-01-27 17:10:01 +1300] [13975] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13975] [INFO] Worker exiting (pid: 13975)
[2023-01-27 17:10:01 +1300] [14145] [INFO] Booting worker with pid: 14145
[2023-01-27 17:10:01 +1300] [13976] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13976] [INFO] Worker exiting (pid: 13976)
[2023-01-27 17:10:01 +1300] [13966] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:10:01 +1300] [13966] [INFO] Worker exiting (pid: 13966)
[2023-01-27 17:10:01 +1300] [14146] [INFO] Booting worker with pid: 14146
[2023-01-27 17:10:02 +1300] [14147] [INFO] Booting worker with pid: 14147
[2023-01-27 17:10:02 +1300] [14149] [INFO] Booting worker with pid: 14149
[2023-01-27 17:10:02 +1300] [14150] [INFO] Booting worker with pid: 14150
[2023-01-27 17:10:02 +1300] [14151] [INFO] Booting worker with pid: 14151
[2023-01-27 17:10:02 +1300] [14152] [INFO] Booting worker with pid: 14152
[2023-01-27 17:10:02 +1300] [14153] [INFO] Booting worker with pid: 14153
[2023-01-27 17:10:03 +1300] [14154] [INFO] Booting worker with pid: 14154
[2023-01-27 17:14:07 +1300] [14147] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14147] [INFO] Worker exiting (pid: 14147)
[2023-01-27 17:14:07 +1300] [14145] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14151] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14145] [INFO] Worker exiting (pid: 14145)
[2023-01-27 17:14:07 +1300] [14151] [INFO] Worker exiting (pid: 14151)
[2023-01-27 17:14:07 +1300] [14146] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14146] [INFO] Worker exiting (pid: 14146)
[2023-01-27 17:14:07 +1300] [14149] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14149] [INFO] Worker exiting (pid: 14149)
[2023-01-27 17:14:07 +1300] [14150] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14154] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14154] [INFO] Worker exiting (pid: 14154)
[2023-01-27 17:14:07 +1300] [14150] [INFO] Worker exiting (pid: 14150)
[2023-01-27 17:14:07 +1300] [14153] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14153] [INFO] Worker exiting (pid: 14153)
[2023-01-27 17:14:07 +1300] [14152] [INFO] Worker reloading: /var/www/piapp/api_app/index.py modified
[2023-01-27 17:14:07 +1300] [14152] [INFO] Worker exiting (pid: 14152)
[2023-01-27 17:14:08 +1300] [14337] [INFO] Booting worker with pid: 14337
[2023-01-27 17:14:08 +1300] [14338] [INFO] Booting worker with pid: 14338
[2023-01-27 17:14:08 +1300] [14339] [INFO] Booting worker with pid: 14339
[2023-01-27 17:14:08 +1300] [14340] [INFO] Booting worker with pid: 14340
[2023-01-27 17:14:08 +1300] [14342] [INFO] Booting worker with pid: 14342
[2023-01-27 17:14:08 +1300] [14343] [INFO] Booting worker with pid: 14343
[2023-01-27 17:14:08 +1300] [14344] [INFO] Booting worker with pid: 14344
[2023-01-27 17:14:08 +1300] [14345] [INFO] Booting worker with pid: 14345
[2023-01-27 17:14:08 +1300] [14346] [INFO] Booting worker with pid: 14346
[2023-01-27 17:15:09 +1300] [14338] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14338] [INFO] Worker exiting (pid: 14338)
[2023-01-27 17:15:09 +1300] [14343] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14343] [INFO] Worker exiting (pid: 14343)
[2023-01-27 17:15:09 +1300] [14337] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14337] [INFO] Worker exiting (pid: 14337)
[2023-01-27 17:15:09 +1300] [14340] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14340] [INFO] Worker exiting (pid: 14340)
[2023-01-27 17:15:09 +1300] [14339] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14339] [INFO] Worker exiting (pid: 14339)
[2023-01-27 17:15:09 +1300] [14346] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14346] [INFO] Worker exiting (pid: 14346)
[2023-01-27 17:15:09 +1300] [14342] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14342] [INFO] Worker exiting (pid: 14342)
[2023-01-27 17:15:09 +1300] [14345] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14345] [INFO] Worker exiting (pid: 14345)
[2023-01-27 17:15:09 +1300] [14344] [INFO] Worker reloading: gunicorn_config.py modified
[2023-01-27 17:15:09 +1300] [14344] [INFO] Worker exiting (pid: 14344)
[2023-01-27 17:15:10 +1300] [14400] [INFO] Booting worker with pid: 14400
[2023-01-27 17:15:10 +1300] [14401] [INFO] Booting worker with pid: 14401
[2023-01-27 17:15:10 +1300] [14402] [INFO] Booting worker with pid: 14402
[2023-01-27 17:15:10 +1300] [14403] [INFO] Booting worker with pid: 14403
[2023-01-27 17:15:10 +1300] [14404] [INFO] Booting worker with pid: 14404
[2023-01-27 17:15:10 +1300] [14405] [INFO] Booting worker with pid: 14405
[2023-01-27 17:15:10 +1300] [14406] [INFO] Booting worker with pid: 14406
[2023-01-27 17:15:10 +1300] [14407] [INFO] Booting worker with pid: 14407
[2023-01-27 17:15:11 +1300] [14408] [INFO] Booting worker with pid: 14408
[2023-01-27 17:16:01 +1300] [14401] [INFO] Worker exiting (pid: 14401)
[2023-01-27 17:16:01 +1300] [14400] [INFO] Worker exiting (pid: 14400)
[2023-01-27 17:16:01 +1300] [11394] [INFO] Handling signal: term
[2023-01-27 17:16:01 +1300] [14402] [INFO] Worker exiting (pid: 14402)
[2023-01-27 17:16:01 +1300] [14404] [INFO] Worker exiting (pid: 14404)
[2023-01-27 17:16:01 +1300] [14403] [INFO] Worker exiting (pid: 14403)
[2023-01-27 17:16:01 +1300] [14406] [INFO] Worker exiting (pid: 14406)
[2023-01-27 17:16:01 +1300] [14407] [INFO] Worker exiting (pid: 14407)
[2023-01-27 17:16:01 +1300] [14408] [INFO] Worker exiting (pid: 14408)
[2023-01-27 17:16:01 +1300] [14405] [INFO] Worker exiting (pid: 14405)
[2023-01-27 17:16:01 +1300] [11394] [WARNING] Worker with pid 14406 was terminated due to signal 15
[2023-01-27 17:16:01 +1300] [11394] [WARNING] Worker with pid 14400 was terminated due to signal 15
[2023-01-27 17:16:03 +1300] [11394] [INFO] Shutting down: Master
[2023-01-27 17:16:25 +1300] [576] [INFO] Starting gunicorn 20.1.0
[2023-01-27 17:16:25 +1300] [576] [INFO] Listening at: unix:flaskrest.sock (576)
[2023-01-27 17:16:25 +1300] [576] [INFO] Using worker: sync
[2023-01-27 17:16:25 +1300] [756] [INFO] Booting worker with pid: 756
[2023-01-27 17:16:25 +1300] [778] [INFO] Booting worker with pid: 778
[2023-01-27 17:16:25 +1300] [783] [INFO] Booting worker with pid: 783
[2023-01-27 17:16:25 +1300] [787] [INFO] Booting worker with pid: 787
[2023-01-27 17:16:25 +1300] [792] [INFO] Booting worker with pid: 792
[2023-01-27 17:16:25 +1300] [802] [INFO] Booting worker with pid: 802
[2023-01-27 17:16:25 +1300] [821] [INFO] Booting worker with pid: 821
[2023-01-27 17:16:25 +1300] [824] [INFO] Booting worker with pid: 824
[2023-01-27 17:16:26 +1300] [843] [INFO] Booting worker with pid: 843
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:756)
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:778)
[2023-01-27 17:17:24 +1300] [756] [INFO] Worker exiting (pid: 756)
[2023-01-27 17:17:24 +1300] [778] [INFO] Worker exiting (pid: 778)
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:783)
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:787)
[2023-01-27 17:17:24 +1300] [783] [INFO] Worker exiting (pid: 783)
[2023-01-27 17:17:24 +1300] [787] [INFO] Worker exiting (pid: 787)
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:792)
[2023-01-27 17:17:24 +1300] [792] [INFO] Worker exiting (pid: 792)
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:802)
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:821)
[2023-01-27 17:17:24 +1300] [802] [INFO] Worker exiting (pid: 802)
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:824)
[2023-01-27 17:17:24 +1300] [821] [INFO] Worker exiting (pid: 821)
[2023-01-27 17:17:24 +1300] [824] [INFO] Worker exiting (pid: 824)
[2023-01-27 17:17:24 +1300] [576] [CRITICAL] WORKER TIMEOUT (pid:843)
[2023-01-27 17:17:24 +1300] [843] [INFO] Worker exiting (pid: 843)
[2023-01-27 17:17:25 +1300] [576] [WARNING] Worker with pid 778 was terminated due to signal 9
[2023-01-27 17:17:25 +1300] [1756] [INFO] Booting worker with pid: 1756
[2023-01-27 17:17:25 +1300] [576] [WARNING] Worker with pid 802 was terminated due to signal 9
[2023-01-27 17:17:26 +1300] [576] [WARNING] Worker with pid 843 was terminated due to signal 9
[2023-01-27 17:17:26 +1300] [1757] [INFO] Booting worker with pid: 1757
[2023-01-27 17:17:26 +1300] [1758] [INFO] Booting worker with pid: 1758
[2023-01-27 17:17:26 +1300] [1759] [INFO] Booting worker with pid: 1759
[2023-01-27 17:17:26 +1300] [1760] [INFO] Booting worker with pid: 1760
[2023-01-27 17:17:26 +1300] [1761] [INFO] Booting worker with pid: 1761
[2023-01-27 17:17:26 +1300] [1762] [INFO] Booting worker with pid: 1762
[2023-01-27 17:17:26 +1300] [1763] [INFO] Booting worker with pid: 1763
[2023-01-27 17:17:26 +1300] [1764] [INFO] Booting worker with pid: 1764
[2023-01-27 17:46:32 +1300] [576] [INFO] Handling signal: term
[2023-01-27 17:46:32 +1300] [1760] [INFO] Worker exiting (pid: 1760)
[2023-01-27 17:46:32 +1300] [1756] [INFO] Worker exiting (pid: 1756)
[2023-01-27 17:46:32 +1300] [1759] [INFO] Worker exiting (pid: 1759)
[2023-01-27 17:46:32 +1300] [1757] [INFO] Worker exiting (pid: 1757)
[2023-01-27 17:46:32 +1300] [1758] [INFO] Worker exiting (pid: 1758)
[2023-01-27 17:46:32 +1300] [1764] [INFO] Worker exiting (pid: 1764)
[2023-01-27 17:46:32 +1300] [1762] [INFO] Worker exiting (pid: 1762)
[2023-01-27 17:46:32 +1300] [1763] [INFO] Worker exiting (pid: 1763)
[2023-01-27 17:46:32 +1300] [1761] [INFO] Worker exiting (pid: 1761)
[2023-01-27 17:46:32 +1300] [576] [WARNING] Worker with pid 1760 was terminated due to signal 15
[2023-01-27 17:46:33 +1300] [576] [INFO] Shutting down: Master
[2023-01-27 17:46:35 +1300] [3127] [INFO] Starting gunicorn 20.1.0
[2023-01-27 17:46:35 +1300] [3127] [INFO] Listening at: unix:flaskrest.sock (3127)
[2023-01-27 17:46:35 +1300] [3127] [INFO] Using worker: sync
[2023-01-27 17:46:35 +1300] [3131] [INFO] Booting worker with pid: 3131
[2023-01-27 17:46:35 +1300] [3132] [INFO] Booting worker with pid: 3132
[2023-01-27 17:46:35 +1300] [3133] [INFO] Booting worker with pid: 3133
[2023-01-27 17:46:35 +1300] [3134] [INFO] Booting worker with pid: 3134
[2023-01-27 17:46:35 +1300] [3135] [INFO] Booting worker with pid: 3135
[2023-01-27 17:46:35 +1300] [3136] [INFO] Booting worker with pid: 3136
[2023-01-27 17:46:35 +1300] [3137] [INFO] Booting worker with pid: 3137
[2023-01-27 17:46:35 +1300] [3138] [INFO] Booting worker with pid: 3138
[2023-01-27 17:46:35 +1300] [3139] [INFO] Booting worker with pid: 3139
[2023-01-27 18:14:31 +1300] [3132] [INFO] Worker exiting (pid: 3132)
[2023-01-27 18:14:31 +1300] [3133] [INFO] Worker exiting (pid: 3133)
[2023-01-27 18:14:31 +1300] [3127] [INFO] Handling signal: term
[2023-01-27 18:14:31 +1300] [3139] [INFO] Worker exiting (pid: 3139)
[2023-01-27 18:14:31 +1300] [3131] [INFO] Worker exiting (pid: 3131)
[2023-01-27 18:14:31 +1300] [3138] [INFO] Worker exiting (pid: 3138)
[2023-01-27 18:14:31 +1300] [3135] [INFO] Worker exiting (pid: 3135)
[2023-01-27 18:14:31 +1300] [3136] [INFO] Worker exiting (pid: 3136)
[2023-01-27 18:14:31 +1300] [3134] [INFO] Worker exiting (pid: 3134)
[2023-01-27 18:14:31 +1300] [3137] [INFO] Worker exiting (pid: 3137)
[2023-01-27 18:14:31 +1300] [3127] [WARNING] Worker with pid 3136 was terminated due to signal 15
[2023-01-27 18:14:32 +1300] [3127] [WARNING] Worker with pid 3139 was terminated due to signal 15
[2023-01-27 18:14:32 +1300] [3127] [WARNING] Worker with pid 3138 was terminated due to signal 15
[2023-01-27 18:14:33 +1300] [3127] [INFO] Shutting down: Master
[2023-01-27 18:14:53 +1300] [578] [INFO] Starting gunicorn 20.1.0
[2023-01-27 18:14:53 +1300] [578] [INFO] Listening at: unix:flaskrest.sock (578)
[2023-01-27 18:14:53 +1300] [578] [INFO] Using worker: sync
[2023-01-27 18:14:53 +1300] [756] [INFO] Booting worker with pid: 756
[2023-01-27 18:14:53 +1300] [757] [INFO] Booting worker with pid: 757
[2023-01-27 18:14:53 +1300] [758] [INFO] Booting worker with pid: 758
[2023-01-27 18:14:53 +1300] [761] [INFO] Booting worker with pid: 761
[2023-01-27 18:14:53 +1300] [772] [INFO] Booting worker with pid: 772
[2023-01-27 18:14:53 +1300] [780] [INFO] Booting worker with pid: 780
[2023-01-27 18:14:53 +1300] [810] [INFO] Booting worker with pid: 810
[2023-01-27 18:14:54 +1300] [818] [INFO] Booting worker with pid: 818
[2023-01-27 18:14:54 +1300] [841] [INFO] Booting worker with pid: 841
[2023-02-03 12:35:21 +1300] [758] [INFO] Worker exiting (pid: 758)
[2023-02-03 12:35:21 +1300] [757] [INFO] Worker exiting (pid: 757)
[2023-02-03 12:35:21 +1300] [818] [INFO] Worker exiting (pid: 818)
[2023-02-03 12:35:21 +1300] [810] [INFO] Worker exiting (pid: 810)
[2023-02-03 12:35:24 +1300] [756] [INFO] Worker exiting (pid: 756)
[2023-02-03 12:35:24 +1300] [761] [INFO] Worker exiting (pid: 761)
[2023-02-03 12:35:24 +1300] [841] [INFO] Worker exiting (pid: 841)
[2023-02-03 12:35:24 +1300] [772] [INFO] Worker exiting (pid: 772)
[2023-02-03 12:35:24 +1300] [780] [INFO] Worker exiting (pid: 780)
[2023-02-03 12:35:24 +1300] [578] [INFO] Handling signal: term
[2023-02-03 12:35:30 +1300] [578] [WARNING] Worker with pid 758 was terminated due to signal 15
[2023-02-03 12:35:30 +1300] [578] [WARNING] Worker with pid 810 was terminated due to signal 15
[2023-02-03 12:35:30 +1300] [578] [WARNING] Worker with pid 818 was terminated due to signal 15
[2023-02-03 12:35:30 +1300] [578] [WARNING] Worker with pid 757 was terminated due to signal 15
[2023-02-03 12:35:39 +1300] [578] [INFO] Shutting down: Master
[2023-02-03 12:35:55 +1300] [507] [INFO] Starting gunicorn 20.1.0
[2023-02-03 12:35:55 +1300] [507] [INFO] Listening at: unix:flaskrest.sock (507)
[2023-02-03 12:35:55 +1300] [507] [INFO] Using worker: sync
[2023-02-03 12:35:55 +1300] [648] [INFO] Booting worker with pid: 648
[2023-02-03 12:35:55 +1300] [649] [INFO] Booting worker with pid: 649
[2023-02-03 12:35:55 +1300] [650] [INFO] Booting worker with pid: 650
[2023-02-03 12:35:55 +1300] [651] [INFO] Booting worker with pid: 651
[2023-02-03 12:35:55 +1300] [652] [INFO] Booting worker with pid: 652
[2023-02-03 12:35:55 +1300] [653] [INFO] Booting worker with pid: 653
[2023-02-03 12:35:55 +1300] [654] [INFO] Booting worker with pid: 654
[2023-02-03 12:35:55 +1300] [655] [INFO] Booting worker with pid: 655
[2023-02-03 12:35:55 +1300] [656] [INFO] Booting worker with pid: 656
[2023-02-03 12:36:55 +1300] [507] [CRITICAL] WORKER TIMEOUT (pid:648)
[2023-02-03 12:36:55 +1300] [507] [CRITICAL] WORKER TIMEOUT (pid:649)
[2023-02-03 12:36:55 +1300] [507] [CRITICAL] WORKER TIMEOUT (pid:650)
[2023-02-03 12:36:55 +1300] [648] [INFO] Worker exiting (pid: 648)
[2023-02-03 12:36:55 +1300] [507] [CRITICAL] WORKER TIMEOUT (pid:653)
[2023-02-03 12:36:55 +1300] [649] [INFO] Worker exiting (pid: 649)
[2023-02-03 12:36:55 +1300] [653] [INFO] Worker exiting (pid: 653)
[2023-02-03 12:36:55 +1300] [650] [INFO] Worker exiting (pid: 650)
[2023-02-03 12:36:55 +1300] [507] [CRITICAL] WORKER TIMEOUT (pid:654)
[2023-02-03 12:36:55 +1300] [507] [CRITICAL] WORKER TIMEOUT (pid:655)
[2023-02-03 12:36:55 +1300] [654] [INFO] Worker exiting (pid: 654)
[2023-02-03 12:36:55 +1300] [655] [INFO] Worker exiting (pid: 655)
[2023-02-03 12:36:56 +1300] [507] [CRITICAL] WORKER TIMEOUT (pid:656)
[2023-02-03 12:36:56 +1300] [656] [INFO] Worker exiting (pid: 656)
[2023-02-03 12:36:56 +1300] [507] [WARNING] Worker with pid 648 was terminated due to signal 9
[2023-02-03 12:36:56 +1300] [507] [WARNING] Worker with pid 650 was terminated due to signal 9
[2023-02-03 12:36:56 +1300] [507] [WARNING] Worker with pid 655 was terminated due to signal 9
[2023-02-03 12:36:56 +1300] [1062] [INFO] Booting worker with pid: 1062
[2023-02-03 12:36:56 +1300] [507] [WARNING] Worker with pid 649 was terminated due to signal 9
[2023-02-03 12:36:56 +1300] [507] [WARNING] Worker with pid 654 was terminated due to signal 9
[2023-02-03 12:36:56 +1300] [507] [WARNING] Worker with pid 653 was terminated due to signal 9
[2023-02-03 12:36:56 +1300] [1063] [INFO] Booting worker with pid: 1063
[2023-02-03 12:36:57 +1300] [1064] [INFO] Booting worker with pid: 1064
[2023-02-03 12:36:57 +1300] [1065] [INFO] Booting worker with pid: 1065
[2023-02-03 12:36:57 +1300] [1066] [INFO] Booting worker with pid: 1066
[2023-02-03 12:36:57 +1300] [1067] [INFO] Booting worker with pid: 1067
[2023-02-03 12:36:57 +1300] [1068] [INFO] Booting worker with pid: 1068
[2023-02-03 12:40:49 +1300] [506] [INFO] Starting gunicorn 20.1.0
[2023-02-03 12:40:49 +1300] [506] [INFO] Listening at: unix:flaskrest.sock (506)
[2023-02-03 12:40:49 +1300] [506] [INFO] Using worker: sync
[2023-02-03 12:40:49 +1300] [649] [INFO] Booting worker with pid: 649
[2023-02-03 12:40:49 +1300] [650] [INFO] Booting worker with pid: 650
[2023-02-03 12:40:50 +1300] [651] [INFO] Booting worker with pid: 651
[2023-02-03 12:40:50 +1300] [652] [INFO] Booting worker with pid: 652
[2023-02-03 12:40:50 +1300] [653] [INFO] Booting worker with pid: 653
[2023-02-03 12:40:50 +1300] [654] [INFO] Booting worker with pid: 654
[2023-02-03 12:40:50 +1300] [655] [INFO] Booting worker with pid: 655
[2023-02-03 12:40:50 +1300] [656] [INFO] Booting worker with pid: 656
[2023-02-03 12:40:50 +1300] [657] [INFO] Booting worker with pid: 657
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:649)
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:650)
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:651)
[2023-02-03 12:42:35 +1300] [649] [INFO] Worker exiting (pid: 649)
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:652)
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:653)
[2023-02-03 12:42:35 +1300] [651] [INFO] Worker exiting (pid: 651)
[2023-02-03 12:42:35 +1300] [652] [INFO] Worker exiting (pid: 652)
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:654)
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:655)
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:656)
[2023-02-03 12:42:35 +1300] [655] [INFO] Worker exiting (pid: 655)
[2023-02-03 12:42:35 +1300] [656] [INFO] Worker exiting (pid: 656)
[2023-02-03 12:42:35 +1300] [653] [INFO] Worker exiting (pid: 653)
[2023-02-03 12:42:35 +1300] [654] [INFO] Worker exiting (pid: 654)
[2023-02-03 12:42:35 +1300] [650] [INFO] Worker exiting (pid: 650)
[2023-02-03 12:42:35 +1300] [506] [CRITICAL] WORKER TIMEOUT (pid:657)
[2023-02-03 12:42:35 +1300] [657] [INFO] Worker exiting (pid: 657)
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 651 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 656 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 649 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 650 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [1008] [INFO] Booting worker with pid: 1008
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 655 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 657 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 654 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 653 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [506] [WARNING] Worker with pid 652 was terminated due to signal 9
[2023-02-03 12:42:37 +1300] [1009] [INFO] Booting worker with pid: 1009
[2023-02-03 12:42:37 +1300] [1010] [INFO] Booting worker with pid: 1010
[2023-02-03 12:42:37 +1300] [1011] [INFO] Booting worker with pid: 1011
[2023-02-03 12:42:37 +1300] [1012] [INFO] Booting worker with pid: 1012
[2023-02-03 12:42:37 +1300] [1013] [INFO] Booting worker with pid: 1013
[2023-02-03 12:42:37 +1300] [1014] [INFO] Booting worker with pid: 1014
[2023-02-03 12:42:37 +1300] [1015] [INFO] Booting worker with pid: 1015
[2023-02-03 12:42:37 +1300] [1016] [INFO] Booting worker with pid: 1016
[2023-02-03 12:46:29 +1300] [473] [INFO] Starting gunicorn 20.1.0
[2023-02-03 12:46:29 +1300] [473] [INFO] Listening at: unix:flaskrest.sock (473)
[2023-02-03 12:46:29 +1300] [473] [INFO] Using worker: sync
[2023-02-03 12:46:29 +1300] [613] [INFO] Booting worker with pid: 613
[2023-02-03 12:46:30 +1300] [614] [INFO] Booting worker with pid: 614
[2023-02-03 12:46:30 +1300] [615] [INFO] Booting worker with pid: 615
[2023-02-03 12:46:30 +1300] [616] [INFO] Booting worker with pid: 616
[2023-02-03 12:46:30 +1300] [617] [INFO] Booting worker with pid: 617
[2023-02-03 12:46:30 +1300] [618] [INFO] Booting worker with pid: 618
[2023-02-03 12:46:30 +1300] [619] [INFO] Booting worker with pid: 619
[2023-02-03 12:46:30 +1300] [621] [INFO] Booting worker with pid: 621
[2023-02-03 12:46:30 +1300] [622] [INFO] Booting worker with pid: 622
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:613)
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:614)
[2023-02-03 12:50:01 +1300] [613] [INFO] Worker exiting (pid: 613)
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:615)
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:616)
[2023-02-03 12:50:01 +1300] [614] [INFO] Worker exiting (pid: 614)
[2023-02-03 12:50:01 +1300] [616] [INFO] Worker exiting (pid: 616)
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:617)
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:618)
[2023-02-03 12:50:01 +1300] [617] [INFO] Worker exiting (pid: 617)
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:619)
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:621)
[2023-02-03 12:50:01 +1300] [618] [INFO] Worker exiting (pid: 618)
[2023-02-03 12:50:01 +1300] [621] [INFO] Worker exiting (pid: 621)
[2023-02-03 12:50:01 +1300] [615] [INFO] Worker exiting (pid: 615)
[2023-02-03 12:50:01 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:622)
[2023-02-03 12:50:01 +1300] [619] [INFO] Worker exiting (pid: 619)
[2023-02-03 12:50:01 +1300] [622] [INFO] Worker exiting (pid: 622)
[2023-02-03 12:50:01 +1300] [1027] [INFO] Booting worker with pid: 1027
[2023-02-03 12:50:01 +1300] [473] [WARNING] Worker with pid 613 was terminated due to signal 9
[2023-02-03 12:50:01 +1300] [473] [WARNING] Worker with pid 617 was terminated due to signal 9
[2023-02-03 12:50:01 +1300] [473] [WARNING] Worker with pid 616 was terminated due to signal 9
[2023-02-03 12:50:01 +1300] [473] [WARNING] Worker with pid 619 was terminated due to signal 9
[2023-02-03 12:50:01 +1300] [473] [WARNING] Worker with pid 615 was terminated due to signal 9
[2023-02-03 12:50:01 +1300] [473] [WARNING] Worker with pid 622 was terminated due to signal 9
[2023-02-03 12:50:01 +1300] [473] [WARNING] Worker with pid 614 was terminated due to signal 9
[2023-02-03 12:50:01 +1300] [473] [WARNING] Worker with pid 618 was terminated due to signal 9
[2023-02-03 12:50:01 +1300] [1028] [INFO] Booting worker with pid: 1028
[2023-02-03 12:50:02 +1300] [1029] [INFO] Booting worker with pid: 1029
[2023-02-03 12:50:02 +1300] [1030] [INFO] Booting worker with pid: 1030
[2023-02-03 12:50:02 +1300] [1031] [INFO] Booting worker with pid: 1031
[2023-02-03 12:50:02 +1300] [1032] [INFO] Booting worker with pid: 1032
[2023-02-03 12:50:02 +1300] [1035] [INFO] Booting worker with pid: 1035
[2023-02-03 12:50:02 +1300] [1046] [INFO] Booting worker with pid: 1046
[2023-02-03 12:50:02 +1300] [1060] [INFO] Booting worker with pid: 1060
[2023-02-03 12:51:46 +1300] [473] [INFO] Starting gunicorn 20.1.0
[2023-02-03 12:51:46 +1300] [473] [INFO] Listening at: unix:flaskrest.sock (473)
[2023-02-03 12:51:46 +1300] [473] [INFO] Using worker: sync
[2023-02-03 12:51:46 +1300] [630] [INFO] Booting worker with pid: 630
[2023-02-03 12:51:46 +1300] [633] [INFO] Booting worker with pid: 633
[2023-02-03 12:51:47 +1300] [637] [INFO] Booting worker with pid: 637
[2023-02-03 12:51:47 +1300] [639] [INFO] Booting worker with pid: 639
[2023-02-03 12:51:47 +1300] [640] [INFO] Booting worker with pid: 640
[2023-02-03 12:51:47 +1300] [641] [INFO] Booting worker with pid: 641
[2023-02-03 12:51:47 +1300] [644] [INFO] Booting worker with pid: 644
[2023-02-03 12:51:47 +1300] [647] [INFO] Booting worker with pid: 647
[2023-02-03 12:51:47 +1300] [651] [INFO] Booting worker with pid: 651
[2023-02-03 12:59:23 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:637)
[2023-02-03 12:59:23 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:644)
[2023-02-03 12:59:23 +1300] [473] [CRITICAL] WORKER TIMEOUT (pid:647)
[2023-02-03 12:59:23 +1300] [637] [INFO] Worker exiting (pid: 637)
[2023-02-03 12:59:23 +1300] [647] [INFO] Worker exiting (pid: 647)
[2023-02-03 12:59:23 +1300] [644] [INFO] Worker exiting (pid: 644)
[2023-02-03 12:59:23 +1300] [1053] [INFO] Booting worker with pid: 1053
[2023-02-03 12:59:23 +1300] [473] [WARNING] Worker with pid 644 was terminated due to signal 9
[2023-02-03 12:59:23 +1300] [473] [WARNING] Worker with pid 637 was terminated due to signal 9
[2023-02-03 12:59:23 +1300] [1054] [INFO] Booting worker with pid: 1054
[2023-02-03 12:59:23 +1300] [1055] [INFO] Booting worker with pid: 1055
[2023-02-03 12:59:32 +1300] [489] [INFO] Starting gunicorn 20.1.0
[2023-02-03 12:59:32 +1300] [489] [INFO] Listening at: unix:flaskrest.sock (489)
[2023-02-03 12:59:32 +1300] [489] [INFO] Using worker: sync
[2023-02-03 12:59:32 +1300] [634] [INFO] Booting worker with pid: 634
[2023-02-03 12:59:32 +1300] [635] [INFO] Booting worker with pid: 635
[2023-02-03 12:59:32 +1300] [636] [INFO] Booting worker with pid: 636
[2023-02-03 12:59:33 +1300] [637] [INFO] Booting worker with pid: 637
[2023-02-03 12:59:33 +1300] [638] [INFO] Booting worker with pid: 638
[2023-02-03 12:59:33 +1300] [639] [INFO] Booting worker with pid: 639
[2023-02-03 12:59:33 +1300] [640] [INFO] Booting worker with pid: 640
[2023-02-03 12:59:33 +1300] [641] [INFO] Booting worker with pid: 641
[2023-02-03 12:59:33 +1300] [642] [INFO] Booting worker with pid: 642
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:634)
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:635)
[2023-02-03 13:00:45 +1300] [634] [INFO] Worker exiting (pid: 634)
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:636)
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:637)
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:638)
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:639)
[2023-02-03 13:00:45 +1300] [637] [INFO] Worker exiting (pid: 637)
[2023-02-03 13:00:45 +1300] [639] [INFO] Worker exiting (pid: 639)
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:640)
[2023-02-03 13:00:45 +1300] [636] [INFO] Worker exiting (pid: 636)
[2023-02-03 13:00:45 +1300] [638] [INFO] Worker exiting (pid: 638)
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:641)
[2023-02-03 13:00:45 +1300] [489] [CRITICAL] WORKER TIMEOUT (pid:642)
[2023-02-03 13:00:45 +1300] [641] [INFO] Worker exiting (pid: 641)
[2023-02-03 13:00:45 +1300] [642] [INFO] Worker exiting (pid: 642)
[2023-02-03 13:00:45 +1300] [640] [INFO] Worker exiting (pid: 640)
[2023-02-03 13:00:45 +1300] [635] [INFO] Worker exiting (pid: 635)
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 638 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 635 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [1045] [INFO] Booting worker with pid: 1045
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 636 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 640 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 641 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 634 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 637 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 642 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [489] [WARNING] Worker with pid 639 was terminated due to signal 9
[2023-02-03 13:00:46 +1300] [1046] [INFO] Booting worker with pid: 1046
[2023-02-03 13:00:46 +1300] [1047] [INFO] Booting worker with pid: 1047
[2023-02-03 13:00:47 +1300] [1048] [INFO] Booting worker with pid: 1048
[2023-02-03 13:00:47 +1300] [1049] [INFO] Booting worker with pid: 1049
[2023-02-03 13:00:47 +1300] [1050] [INFO] Booting worker with pid: 1050
[2023-02-03 13:00:47 +1300] [1051] [INFO] Booting worker with pid: 1051
[2023-02-03 13:00:47 +1300] [1052] [INFO] Booting worker with pid: 1052
[2023-02-03 13:00:47 +1300] [1053] [INFO] Booting worker with pid: 1053
[2023-02-03 13:08:56 +1300] [491] [INFO] Starting gunicorn 20.1.0
[2023-02-03 13:08:56 +1300] [491] [INFO] Listening at: unix:flaskrest.sock (491)
[2023-02-03 13:08:56 +1300] [491] [INFO] Using worker: sync
[2023-02-03 13:08:56 +1300] [639] [INFO] Booting worker with pid: 639
[2023-02-03 13:08:56 +1300] [640] [INFO] Booting worker with pid: 640
[2023-02-03 13:08:56 +1300] [641] [INFO] Booting worker with pid: 641
[2023-02-03 13:08:56 +1300] [642] [INFO] Booting worker with pid: 642
[2023-02-03 13:08:56 +1300] [643] [INFO] Booting worker with pid: 643
[2023-02-03 13:08:56 +1300] [644] [INFO] Booting worker with pid: 644
[2023-02-03 13:08:56 +1300] [645] [INFO] Booting worker with pid: 645
[2023-02-03 13:08:56 +1300] [646] [INFO] Booting worker with pid: 646
[2023-02-03 13:08:56 +1300] [647] [INFO] Booting worker with pid: 647
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:639)
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:640)
[2023-02-03 13:15:15 +1300] [639] [INFO] Worker exiting (pid: 639)
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:641)
[2023-02-03 13:15:15 +1300] [640] [INFO] Worker exiting (pid: 640)
[2023-02-03 13:15:15 +1300] [641] [INFO] Worker exiting (pid: 641)
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:642)
[2023-02-03 13:15:15 +1300] [642] [INFO] Worker exiting (pid: 642)
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:643)
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:644)
[2023-02-03 13:15:15 +1300] [643] [INFO] Worker exiting (pid: 643)
[2023-02-03 13:15:15 +1300] [644] [INFO] Worker exiting (pid: 644)
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:645)
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:646)
[2023-02-03 13:15:15 +1300] [645] [INFO] Worker exiting (pid: 645)
[2023-02-03 13:15:15 +1300] [491] [CRITICAL] WORKER TIMEOUT (pid:647)
[2023-02-03 13:15:15 +1300] [646] [INFO] Worker exiting (pid: 646)
[2023-02-03 13:15:15 +1300] [647] [INFO] Worker exiting (pid: 647)
[2023-02-03 13:15:16 +1300] [990] [INFO] Booting worker with pid: 990
[2023-02-03 13:15:16 +1300] [491] [WARNING] Worker with pid 642 was terminated due to signal 9
[2023-02-03 13:15:16 +1300] [491] [WARNING] Worker with pid 647 was terminated due to signal 9
[2023-02-03 13:15:16 +1300] [491] [WARNING] Worker with pid 646 was terminated due to signal 9
[2023-02-03 13:15:16 +1300] [491] [WARNING] Worker with pid 640 was terminated due to signal 9
[2023-02-03 13:15:16 +1300] [491] [WARNING] Worker with pid 644 was terminated due to signal 9
[2023-02-03 13:15:16 +1300] [491] [WARNING] Worker with pid 645 was terminated due to signal 9
[2023-02-03 13:15:16 +1300] [491] [WARNING] Worker with pid 643 was terminated due to signal 9
[2023-02-03 13:15:16 +1300] [491] [WARNING] Worker with pid 641 was terminated due to signal 9
[2023-02-03 13:15:16 +1300] [991] [INFO] Booting worker with pid: 991
[2023-02-03 13:15:16 +1300] [992] [INFO] Booting worker with pid: 992
[2023-02-03 13:15:16 +1300] [993] [INFO] Booting worker with pid: 993
[2023-02-03 13:15:16 +1300] [994] [INFO] Booting worker with pid: 994
[2023-02-03 13:15:16 +1300] [995] [INFO] Booting worker with pid: 995
[2023-02-03 13:15:16 +1300] [996] [INFO] Booting worker with pid: 996
[2023-02-03 13:15:16 +1300] [998] [INFO] Booting worker with pid: 998
[2023-02-03 13:15:16 +1300] [1000] [INFO] Booting worker with pid: 1000
[2023-02-03 13:17:00 +1300] [490] [INFO] Starting gunicorn 20.1.0
[2023-02-03 13:17:00 +1300] [490] [INFO] Listening at: unix:flaskrest.sock (490)
[2023-02-03 13:17:00 +1300] [490] [INFO] Using worker: sync
[2023-02-03 13:17:00 +1300] [638] [INFO] Booting worker with pid: 638
[2023-02-03 13:17:00 +1300] [639] [INFO] Booting worker with pid: 639
[2023-02-03 13:17:00 +1300] [640] [INFO] Booting worker with pid: 640
[2023-02-03 13:17:00 +1300] [641] [INFO] Booting worker with pid: 641
[2023-02-03 13:17:00 +1300] [643] [INFO] Booting worker with pid: 643
[2023-02-03 13:17:00 +1300] [644] [INFO] Booting worker with pid: 644
[2023-02-03 13:17:00 +1300] [645] [INFO] Booting worker with pid: 645
[2023-02-03 13:17:00 +1300] [646] [INFO] Booting worker with pid: 646
[2023-02-03 13:17:00 +1300] [647] [INFO] Booting worker with pid: 647
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:638)
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:639)
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:640)
[2023-02-03 13:19:56 +1300] [638] [INFO] Worker exiting (pid: 638)
[2023-02-03 13:19:56 +1300] [639] [INFO] Worker exiting (pid: 639)
[2023-02-03 13:19:56 +1300] [640] [INFO] Worker exiting (pid: 640)
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:641)
[2023-02-03 13:19:56 +1300] [641] [INFO] Worker exiting (pid: 641)
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:643)
[2023-02-03 13:19:56 +1300] [643] [INFO] Worker exiting (pid: 643)
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:644)
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:645)
[2023-02-03 13:19:56 +1300] [644] [INFO] Worker exiting (pid: 644)
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:646)
[2023-02-03 13:19:56 +1300] [490] [CRITICAL] WORKER TIMEOUT (pid:647)
[2023-02-03 13:19:56 +1300] [645] [INFO] Worker exiting (pid: 645)
[2023-02-03 13:19:56 +1300] [646] [INFO] Worker exiting (pid: 646)
[2023-02-03 13:19:56 +1300] [647] [INFO] Worker exiting (pid: 647)
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 638 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 641 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [1053] [INFO] Booting worker with pid: 1053
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 644 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 645 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 646 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 647 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 639 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 643 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [490] [WARNING] Worker with pid 640 was terminated due to signal 9
[2023-02-03 13:19:57 +1300] [1054] [INFO] Booting worker with pid: 1054
[2023-02-03 13:19:57 +1300] [1055] [INFO] Booting worker with pid: 1055
[2023-02-03 13:19:57 +1300] [1056] [INFO] Booting worker with pid: 1056
[2023-02-03 13:19:57 +1300] [1057] [INFO] Booting worker with pid: 1057
[2023-02-03 13:19:57 +1300] [1058] [INFO] Booting worker with pid: 1058
[2023-02-03 13:19:57 +1300] [1059] [INFO] Booting worker with pid: 1059
[2023-02-03 13:19:57 +1300] [1060] [INFO] Booting worker with pid: 1060
[2023-02-03 13:19:57 +1300] [1061] [INFO] Booting worker with pid: 1061
[2023-02-03 15:19:13 +1300] [5924] [INFO] Starting gunicorn 20.1.0
[2023-02-03 15:19:13 +1300] [5924] [INFO] Listening at: unix:flaskrest.sock (5924)
[2023-02-03 15:19:13 +1300] [5924] [INFO] Using worker: sync
[2023-02-03 15:19:13 +1300] [5927] [INFO] Booting worker with pid: 5927
[2023-02-03 15:19:13 +1300] [5927] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:13 +1300] [5927] [INFO] Worker exiting (pid: 5927)
[2023-02-03 15:19:13 +1300] [5928] [INFO] Booting worker with pid: 5928
[2023-02-03 15:19:13 +1300] [5929] [INFO] Booting worker with pid: 5929
[2023-02-03 15:19:13 +1300] [5928] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:13 +1300] [5928] [INFO] Worker exiting (pid: 5928)
[2023-02-03 15:19:13 +1300] [5929] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:13 +1300] [5929] [INFO] Worker exiting (pid: 5929)
[2023-02-03 15:19:13 +1300] [5931] [INFO] Booting worker with pid: 5931
[2023-02-03 15:19:13 +1300] [5935] [INFO] Booting worker with pid: 5935
[2023-02-03 15:19:13 +1300] [5931] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:13 +1300] [5931] [INFO] Worker exiting (pid: 5931)
[2023-02-03 15:19:13 +1300] [5940] [INFO] Booting worker with pid: 5940
[2023-02-03 15:19:13 +1300] [5935] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:13 +1300] [5935] [INFO] Worker exiting (pid: 5935)
[2023-02-03 15:19:13 +1300] [5940] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:13 +1300] [5940] [INFO] Worker exiting (pid: 5940)
[2023-02-03 15:19:13 +1300] [5952] [INFO] Booting worker with pid: 5952
[2023-02-03 15:19:13 +1300] [5956] [INFO] Booting worker with pid: 5956
[2023-02-03 15:19:13 +1300] [5952] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:14 +1300] [5952] [INFO] Worker exiting (pid: 5952)
[2023-02-03 15:19:14 +1300] [5956] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:14 +1300] [5956] [INFO] Worker exiting (pid: 5956)
[2023-02-03 15:19:14 +1300] [5958] [INFO] Booting worker with pid: 5958
[2023-02-03 15:19:14 +1300] [5924] [WARNING] Worker with pid 5929 was terminated due to signal 15
[2023-02-03 15:19:14 +1300] [5924] [WARNING] Worker with pid 5931 was terminated due to signal 15
[2023-02-03 15:19:14 +1300] [5924] [WARNING] Worker with pid 5935 was terminated due to signal 15
[2023-02-03 15:19:14 +1300] [5924] [WARNING] Worker with pid 5952 was terminated due to signal 15
[2023-02-03 15:19:14 +1300] [5924] [WARNING] Worker with pid 5956 was terminated due to signal 15
[2023-02-03 15:19:14 +1300] [5924] [WARNING] Worker with pid 5940 was terminated due to signal 15
[2023-02-03 15:19:14 +1300] [5958] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/hamish3011/Desktop/piapp/piapp/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hamish3011/Desktop/piapp/wsgi.py", line 1, in <module>
    from api_app.index import app
  File "/home/hamish3011/Desktop/piapp/api_app/index.py", line 1, in <module>
    from flask import Flask, jsonify, request, render_template, url_for, flash, redirect
ModuleNotFoundError: No module named 'flask'
[2023-02-03 15:19:14 +1300] [5958] [INFO] Worker exiting (pid: 5958)
[2023-02-03 15:23:02 +1300] [6128] [INFO] Starting gunicorn 20.1.0
[2023-02-03 15:23:02 +1300] [6128] [INFO] Listening at: unix:flaskrest.sock (6128)
[2023-02-03 15:23:02 +1300] [6128] [INFO] Using worker: sync
[2023-02-03 15:23:02 +1300] [6132] [INFO] Booting worker with pid: 6132
[2023-02-03 15:23:02 +1300] [6134] [INFO] Booting worker with pid: 6134
[2023-02-03 15:23:02 +1300] [6135] [INFO] Booting worker with pid: 6135
[2023-02-03 15:23:02 +1300] [6136] [INFO] Booting worker with pid: 6136
[2023-02-03 15:23:02 +1300] [6137] [INFO] Booting worker with pid: 6137
[2023-02-03 15:23:02 +1300] [6138] [INFO] Booting worker with pid: 6138
[2023-02-03 15:23:02 +1300] [6139] [INFO] Booting worker with pid: 6139
[2023-02-03 15:23:02 +1300] [6140] [INFO] Booting worker with pid: 6140
[2023-02-03 15:23:02 +1300] [6141] [INFO] Booting worker with pid: 6141
